# Generated by Django 6.0.4 on 2026-04-15 06:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre completo del cliente.', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico único.', max_length=254, unique=True)),
                ('dni', models.CharField(help_text='Número de documento (7 u 8 dígitos).', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$')])),
                ('date_of_birth', models.DateField(help_text='Fecha de nacimiento.')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto.', max_length=20, null=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('active', 'Activo'), ('closed', 'Cerrado')], default='lead', help_text='Estado del cliente.', max_length=10)),
                ('company_id', models.UUIDField(blank=True, help_text='ID de la empresa asociada (placeholder).', null=True)),
                ('responsible_user_id', models.UUIDField(blank=True, help_text='ID del usuario responsable (placeholder).', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Indica si el cliente está activo en el sistema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
