# Generated by Django 6.0.4 on 2026-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_remove_client_company_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clientes',
        ),
    ]
