# Generated by Django 6.0.4 on 2026-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_company_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='empresas',
        ),
    ]
