# Generated by Django 6.0.4 on 2026-08-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_rename_cuil_to_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cuit',
            field=models.CharField(help_text='Número de CUIT.', max_length=20, unique=True),
        ),
    ]
