# Generated by Django 6.0.4 on 2026-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pending'), ('En progreso', 'In Progress'), ('Cancelada', 'Cancelled'), ('Completada', 'Done')], default='Pendiente', help_text='Estado actual de la tarea.', max_length=15),
        ),
    ]
