# Generated by Django 6.0.4 on 2026-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tareas',
        ),
    ]
